### ISSUE TITLE
[BUG]Mod Organizer 2 launch error

### ISSUE THREAD

**Issue by Brissinger** [Oghma-Infinium/Fahluaan#6]
**Mod Organizer 2 launch error**
It takes huge amount of time to lauch MO2 with error popup and it hangs when I close game.
Other portable instance of MO2 2.5.0 I have created for Bannerlord works/launch normally.

1. Launch Mod Organizer 2
2. I can start game but after closing MO2 hangs.

[Screenshot]
![Zrzut ekranu 2024-02-12 165958](https://github.com/Oghma-Infinium/Fahluaan/assets/72404411/e6540a12-88b8-4a5a-9e6c-8b9b9bc78583)

**Technical :
 - OS: [Windows 11]
 - CPU: [Ryzen 3600]
 - GPU: [GeForce RTX 3060]
 - RAM: [24 GB]
 - Type of Drive: [M.2]
 - Pagefile [10024]

[mo_interface.log](https://github.com/Oghma-Infinium/Fahluaan/files/14240644/mo_interface.log)
[usvfs-2024-02-12_15-23-54.log](https://github.com/Oghma-Infinium/Fahluaan/files/14240645/usvfs-2024-02-12_15-23-54.log)

**Comment by TazerReloaded** [comment]
Mine also takes a while to start. Maybe because it's an alpha build?
```
[2024-02-13 08:46:28.041 E] nexus: Timed out
[2024-02-13 08:46:39.173 E] [github.cpp:194] Github: request for https://api.github.com/repos/Modorganizer2/modorganizer/releases timed out
[2024-02-13 08:46:41.459 W] QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
```
My internet connection is working fine, no outgoing firewall restrictions.

I updated to MO 2.5.0, which is not trivial, but now the problem seems to be solved. If you want, you can try updating too, but don't blame me if it wrecks your installation (can always use Wabbajack to restore though):
- download MO2: https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.5.0
- delete folders associated with MO2 in your Fahluaan directory (especially plugins) to prevent incompatible files
- extract MO2 to your Fahluaan directory, replace when prompted
- download Fix Game Registry plugin: https://www.nexusmods.com/skyrimspecialedition/mods/105997 and place it inside the "plugins" folder
- download Root Builder plugin: https://www.nexusmods.com/skyrimspecialedition/mods/31720 and place it inside the "plugins" folder
- start MO2, select "Steam", import Nexus categories if you want (should not matter)
- you now should have a working MO 2.5.0

Edit: After some gameplay tests everything seems to work fine. I still occasionally get the Nexus login timeout, so that seems to be unrelated.
I will leave it like this until the next official update. Great list, already had a lot of fun playing!

**Comment by aljoxo** [comment]
The MO error posted is just an error that CrashLogTools gives when it can't connect to the internet. I highly doubt this is related to the MO version at all, but it's strange your fix stopped it happening for you.
